-- CreateEnum
CREATE TYPE "SkillCategory" AS ENUM ('BACKEND', 'DATA', 'INTEGRATIONS', 'INFRASTRUCTURE', 'FRONTEND');

-- AlterTable
ALTER TABLE "Profile"
  ADD COLUMN "headline" STRING NOT NULL DEFAULT '',
  ADD COLUMN "location" STRING NOT NULL DEFAULT '',
  ADD COLUMN "availability" STRING NOT NULL DEFAULT '',
  ADD COLUMN "githubUrl" STRING NOT NULL DEFAULT '',
  ADD COLUMN "telegramUrl" STRING NOT NULL DEFAULT '',
  ADD COLUMN "contactEmail" STRING NOT NULL DEFAULT '',
  ADD COLUMN "resumeUrl" STRING NOT NULL DEFAULT '',
  ADD COLUMN "experience" STRING NOT NULL DEFAULT '',
  ADD COLUMN "highlights" STRING NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "Skill" ADD COLUMN "category" "SkillCategory" NOT NULL DEFAULT 'BACKEND';
